### ISSUE TITLE
No module named 'Cython', although cython is installed and up-to-date

### ISSUE THREAD

**Issue by HartmannSa** [ylabbe/cosypose#22]
Hi,
when I follow the specified installation steps, the command 
`conda env create -n cosypose --file environment.yaml`
always ejects the following error message

`Pip subprocess error:
    ERROR: Command errored out with exit status 1:
     command: /home/rosmatch/anaconda3/envs/cosypose/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-h16j98cf/glumpy/setup.py'"'"'; __file__='"'"'/tmp/pip-install-h16j98cf/glumpy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-h16j98cf/glumpy/pip-egg-info
         cwd: /tmp/pip-install-h16j98cf/glumpy/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-h16j98cf/glumpy/setup.py", line 9, in <module>
        from Cython.Distutils import build_ext
    ModuleNotFoundError: No module named 'Cython'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
failed
CondaEnvException: Pip failed`

However, Cython is installed and up-to-date, as shown by the output on the following commands:
`pip install cython`
`Requirement already satisfied: cython in /home/rosmatch/anaconda3/lib/python3.8/site-packages (0.29.21)`
`pip install --upgrade cython`
`Requirement already up-to-date: cython in /home/rosmatch/anaconda3/lib/python3.8/site-packages (0.29.21)`

I have already tested the installation on three different computers and always get the same error. The system used is Ubuntu 18.04.5 LTS.

I am looking forward to any help I can get.

Here is the complete output:

`Collecting package metadata (repodata.json): done
Solving environment: done
Downloading and Extracting Packages
boost-1.72.0         | 339 KB    | ########################################################## | 100% 
octomap-1.9.5        | 457 KB    | ########################################################## | 100% 
hpp-fcl-1.3.0        | 842 KB    | ########################################################## | 100% 
gmp-6.2.1            | 806 KB    | ########################################################## | 100% 
libtiff-4.1.0        | 618 KB    | ########################################################## | 100% 
pycparser-2.20       | 94 KB     | ########################################################## | 100% 
git-lfs-2.11.0       | 4.1 MB    | ########################################################## | 100% 
eigenpy-2.5.0        | 1.1 MB    | ########################################################## | 100% 
mkl-2020.4           | 215.6 MB  | ########################################################## | 100% 
traitlets-5.0.5      | 81 KB     | ########################################################## | 100% 
libiconv-1.16        | 1.4 MB    | ########################################################## | 100% 
libedit-3.1.20191231 | 121 KB    | ########################################################## | 100% 
libcurl-7.71.1       | 312 KB    | ########################################################## | 100% 
libpng-1.6.37        | 306 KB    | ########################################################## | 100% 
cmake-3.14.0         | 12.2 MB   | ########################################################## | 100% 
pickleshare-0.7.5    | 9 KB      | ########################################################## | 100% 
x264-1!152.20180806  | 1.4 MB    | ########################################################## | 100% 
backcall-0.2.0       | 13 KB     | ########################################################## | 100% 
gnutls-3.6.13        | 2.0 MB    | ########################################################## | 100% 
rhash-1.3.6          | 140 KB    | ########################################################## | 100% 
xz-5.2.5             | 343 KB    | ########################################################## | 100% 
readline-8.0         | 281 KB    | ########################################################## | 100% 
libwebp-base-1.1.0   | 864 KB    | ########################################################## | 100% 
zstd-1.4.5           | 712 KB    | ########################################################## | 100% 
libstdcxx-ng-9.3.0   | 4.0 MB    | ########################################################## | 100% 
ffmpeg-4.2.3         | 80.2 MB   | ########################################################## | 100% 
sqlite-3.33.0        | 1.4 MB    | ########################################################## | 100% 
_openmp_mutex-4.5    | 5 KB      | ########################################################## | 100% 
libgcc-ng-9.3.0      | 7.8 MB    | ########################################################## | 100% 
libblas-3.8.0        | 11 KB     | ########################################################## | 100% 
ipython_genutils-0.2 | 21 KB     | ########################################################## | 100% 
gcc_linux-64-7.3.0   | 22 KB     | ########################################################## | 100% 
tk-8.6.10            | 3.2 MB    | ########################################################## | 100% 
pexpect-4.8.0        | 47 KB     | ########################################################## | 100% 
boost-cpp-1.72.0     | 16.3 MB   | ########################################################## | 100% 
six-1.15.0           | 14 KB     | ########################################################## | 100% 
libssh2-1.9.0        | 225 KB    | ########################################################## | 100% 
gxx_linux-64-7.3.0   | 21 KB     | ########################################################## | 100% 
libev-4.33           | 104 KB    | ########################################################## | 100% 
gettext-0.19.8.1     | 3.6 MB    | ########################################################## | 100% 
libcblas-3.8.0       | 11 KB     | ########################################################## | 100% 
openssl-1.1.1h       | 2.1 MB    | ########################################################## | 100% 
python_abi-3.7       | 4 KB      | ########################################################## | 100% 
blas-2.17            | 11 KB     | ########################################################## | 100% 
llvm-openmp-11.0.0   | 2.8 MB    | ########################################################## | 100% 
freetype-2.10.4      | 912 KB    | ########################################################## | 100% 
cudatoolkit-10.1.243 | 347.4 MB  | ########################################################## | 100% 
libgfortran4-7.5.0   | 1.3 MB    | ########################################################## | 100% 
console_bridge-1.0.1 | 17 KB     | ########################################################## | 100% 
numpy-1.17.4         | 4 KB      | ########################################################## | 100% 
numpy-base-1.17.4    | 4.1 MB    | ########################################################## | 100% 
wheel-0.35.1         | 29 KB     | ########################################################## | 100% 
icu-68.1             | 13.0 MB   | ########################################################## | 100% 
expat-2.2.9          | 191 KB    | ########################################################## | 100% 
tinyxml-2.6.2        | 60 KB     | ########################################################## | 100% 
cffi-1.14.4          | 224 KB    | ########################################################## | 100% 
nettle-3.6           | 6.5 MB    | ########################################################## | 100% 
certifi-2020.11.8    | 150 KB    | ########################################################## | 100% 
perl-5.26.2          | 15.4 MB   | ########################################################## | 100% 
pytorch-1.3.1        | 428.0 MB  | ########################################################## | 100% 
gcc_impl_linux-64-7. | 41.9 MB   | ########################################################## | 100% 
binutils_impl_linux- | 9.2 MB    | ########################################################## | 100% 
setuptools-49.6.0    | 944 KB    | ########################################################## | 100% 
bzip2-1.0.8          | 398 KB    | ########################################################## | 100% 
liblapack-3.8.0      | 11 KB     | ########################################################## | 100% 
backports.functools_ | 8 KB      | ########################################################## | 100% 
decorator-4.4.2      | 11 KB     | ########################################################## | 100% 
libgfortran-ng-7.5.0 | 22 KB     | ########################################################## | 100% 
eigen-3.3.8          | 971 KB    | ########################################################## | 100% 
pinocchio-2.3.1      | 3.3 MB    | ########################################################## | 100% 
git-2.28.0           | 15.9 MB   | ########################################################## | 100% 
wcwidth-0.2.5        | 33 KB     | ########################################################## | 100% 
libffi-3.2.1         | 47 KB     | ########################################################## | 100% 
gxx_impl_linux-64-7. | 15.0 MB   | ########################################################## | 100% 
c-ares-1.17.1        | 111 KB    | ########################################################## | 100% 
ninja-1.10.1         | 1.9 MB    | ########################################################## | 100% 
libuv-1.40.0         | 920 KB    | ########################################################## | 100% 
liblapacke-3.8.0     | 11 KB     | ########################################################## | 100% 
olefile-0.46         | 32 KB     | ########################################################## | 100% 
openh264-2.1.1       | 1.5 MB    | ########################################################## | 100% 
pip-19.3.1           | 1.9 MB    | ########################################################## | 100% 
rclone-1.52.3        | 22.1 MB   | ########################################################## | 100% 
pygments-2.7.2       | 707 KB    | ########################################################## | 100% 
jpeg-9d              | 264 KB    | ########################################################## | 100% 
urdfdom-2.3.3        | 126 KB    | ########################################################## | 100% 
assimp-4.1.0         | 32.2 MB   | ########################################################## | 100% 
zlib-1.2.11          | 106 KB    | ########################################################## | 100% 
ca-certificates-2020 | 145 KB    | ########################################################## | 100% 
curl-7.71.1          | 139 KB    | ########################################################## | 100% 
ld_impl_linux-64-2.3 | 616 KB    | ########################################################## | 100% 
pillow-6.0.0         | 616 KB    | ########################################################## | 100% 
krb5-1.17.2          | 1.4 MB    | ########################################################## | 100% 
ptyprocess-0.6.0     | 15 KB     | ########################################################## | 100% 
ncurses-6.2          | 985 KB    | ########################################################## | 100% 
ipython-7.19.0       | 1.1 MB    | ########################################################## | 100% 
backports-1.0        | 4 KB      | ########################################################## | 100% 
lame-3.100           | 498 KB    | ########################################################## | 100% 
libopenblas-0.3.10   | 7.8 MB    | ########################################################## | 100% 
libnghttp2-1.41.0    | 774 KB    | ########################################################## | 100% 
_libgcc_mutex-0.1    | 3 KB      | ########################################################## | 100% 
torchvision-0.4.2    | 14.9 MB   | ########################################################## | 100% 
parso-0.7.1          | 70 KB     | ########################################################## | 100% 
jedi-0.17.2          | 948 KB    | ########################################################## | 100% 
lz4-c-1.9.2          | 203 KB    | ########################################################## | 100% 
urdfdom_headers-1.0. | 16 KB     | ########################################################## | 100% 
python-3.7.6         | 53.0 MB   | ########################################################## | 100% 
binutils_linux-64-2. | 21 KB     | ########################################################## | 100% 
pcre-8.44            | 261 KB    | ########################################################## | 100% 
prompt-toolkit-3.0.8 | 237 KB    | ########################################################## | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Installing pip dependencies: / Ran pip subprocess with arguments:
['/home/rosmatch/anaconda3/envs/cosypose/bin/python', '-m', 'pip', 'install', '-U', '-r', '/home/rosmatch/cosypose/condaenv.7xe_glgc.requirements.txt']
Pip subprocess output:
Processing ./deps/bullet3
Processing ./deps/job-runner
Collecting imageio==2.6.1
  Downloading https://files.pythonhosted.org/packages/1a/de/f7f985018f462ceeffada7f6e609919fbcc934acd9301929cba14bc2c24a/imageio-2.6.1-py3-none-any.whl (3.3MB)
Collecting simplejson==3.17.0
  Downloading https://files.pythonhosted.org/packages/98/87/a7b98aa9256c8843f92878966dc3d8d914c14aad97e2c5ce4798d5743e07/simplejson-3.17.0.tar.gz (83kB)
Collecting opencv-python==4.1.2.30
  Downloading https://files.pythonhosted.org/packages/d8/38/60de02a4c9013b14478a3f681a62e003c7489d207160a4d7df8705a682e7/opencv_python-4.1.2.30-cp37-cp37m-manylinux1_x86_64.whl (28.3MB)
Collecting opencv-contrib-python==4.4.0.42
  Downloading https://files.pythonhosted.org/packages/63/e0/9540422aa60a8ac6baabf2e3685e32008122e11aee48b955bcc2f7157217/opencv_contrib_python-4.4.0.42-cp37-cp37m-manylinux2014_x86_64.whl (55.6MB)
Collecting torchnet==0.0.4
  Downloading https://files.pythonhosted.org/packages/b7/b2/d7f70a85d3f6b0365517782632f150e3bbc2fb8e998cd69e27deba599aae/torchnet-0.0.4.tar.gz
Collecting tqdm==4.41.1
  Downloading https://files.pythonhosted.org/packages/72/c9/7fc20feac72e79032a7c8138fd0d395dc6d8812b5b9edf53c3afd0b31017/tqdm-4.41.1-py2.py3-none-any.whl (56kB)
Collecting lxml==4.4.2
  Downloading https://files.pythonhosted.org/packages/95/60/552fc6e027bc1158ba4691cccfdf6eb77f206f2f21d3c1c5f23b89f68a0e/lxml-4.4.2-cp37-cp37m-manylinux1_x86_64.whl (5.7MB)
Collecting transforms3d==0.3.1
  Downloading https://files.pythonhosted.org/packages/b5/f7/e85809168a548a854d7c1331560c27b4f5381698d29c12e57759192b2bc1/transforms3d-0.3.1.tar.gz (62kB)
Collecting distributed==2.9.1
  Downloading https://files.pythonhosted.org/packages/fe/ad/9c13bac92f0f05973bb6bd179d68e825fc0bb2efbfd1fd2573d57702b410/distributed-2.9.1-py3-none-any.whl (573kB)
Collecting joblib==0.14.1
  Downloading https://files.pythonhosted.org/packages/28/5c/cf6a2b65a321c4a209efcdf64c2689efae2cb62661f8f6f4bb28547cf1bf/joblib-0.14.1-py2.py3-none-any.whl (294kB)
Collecting pandas==0.25.3
  Downloading https://files.pythonhosted.org/packages/63/e0/a1b39cdcb2c391f087a1538bc8a6d62a82d0439693192aef541d7b123769/pandas-0.25.3-cp37-cp37m-manylinux1_x86_64.whl (10.4MB)
Collecting xarray==0.14.1
  Downloading https://files.pythonhosted.org/packages/a8/52/4a561281f536d0902d6279f47fd48894c2c7b7fb078816f18367e9ef46be/xarray-0.14.1-py3-none-any.whl (634kB)
Collecting pyarrow==0.15.1
  Downloading https://files.pythonhosted.org/packages/5a/ee/fd2d696eff911f76ed14feeb51e6db6783dd04abd9b8e14be4cbf48d6088/pyarrow-0.15.1-cp37-cp37m-manylinux2010_x86_64.whl (59.2MB)
Collecting matplotlib==3.1.2
  Downloading https://files.pythonhosted.org/packages/61/42/3e92d7aa64295483fbca20a86c89b34d0cb43cffaadaffe028793902d790/matplotlib-3.1.2-cp37-cp37m-manylinux1_x86_64.whl (13.1MB)
Collecting bokeh==1.4.0
  Downloading https://files.pythonhosted.org/packages/de/70/fdd4b186d8570a737372487cc5547aac885a1270626e3ebf03db1808e4ed/bokeh-1.4.0.tar.gz (32.4MB)
Collecting plyfile==0.7.1
  Downloading https://files.pythonhosted.org/packages/4c/15/434d1d96f9a41fea56cb3290718123d651c56c4b7e53f0249acaf1bf34b6/plyfile-0.7.1.tar.gz
Collecting trimesh==3.5.16
  Downloading https://files.pythonhosted.org/packages/55/8a/423dc7953c15366b6db16014822bb36e260b05daff6237497b0c2c18bd95/trimesh-3.5.16.tar.gz (397kB)
Collecting pycollada==0.6
  Downloading https://files.pythonhosted.org/packages/37/7d/70545d16fed218ce781f74def0cffcfdc3fe46d5c64dfe726b082befb83c/pycollada-0.6.tar.gz (103kB)
Collecting shapely==1.7.0
  Downloading https://files.pythonhosted.org/packages/82/43/3d04326a1e7c1d7dd8791004443b6b0ef425afda7bb2ce669c6d293e4ba0/Shapely-1.7.0-cp37-cp37m-manylinux1_x86_64.whl (1.8MB)
Collecting wget==3.2
  Downloading https://files.pythonhosted.org/packages/47/6a/62e288da7bcda82b935ff0c6cfe542970f04e29c756b0e147251b2fb251f/wget-3.2.zip
Collecting pypng==0.0.20
  Downloading https://files.pythonhosted.org/packages/bc/fb/f719f1ac965e2101aa6ea6f54ef8b40f8fbb033f6ad07c017663467f5147/pypng-0.0.20.tar.gz (649kB)
Collecting PyOpenGL==3.1.0
  Downloading https://files.pythonhosted.org/packages/9c/1d/4544708aaa89f26c97cc09450bb333a23724a320923e74d73e028b3560f9/PyOpenGL-3.1.0.tar.gz (1.2MB)
Collecting Cython==0.29.21
  Downloading https://files.pythonhosted.org/packages/6b/36/d6c18632a339dafa54fd128b0dd2c36c6dc4bc86b8e0d366ccd9f22b480a/Cython-0.29.21-cp37-cp37m-manylinux1_x86_64.whl (2.0MB)
Collecting glumpy==1.1.0
  Downloading https://files.pythonhosted.org/packages/1e/d9/cbc85887ec54406ffe991d42de11445e5dacd052748cf376be6403b40d61/glumpy-1.1.0.tar.gz (503kB)
Pip subprocess error:
    ERROR: Command errored out with exit status 1:
     command: /home/rosmatch/anaconda3/envs/cosypose/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-h16j98cf/glumpy/setup.py'"'"'; __file__='"'"'/tmp/pip-install-h16j98cf/glumpy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-h16j98cf/glumpy/pip-egg-info
         cwd: /tmp/pip-install-h16j98cf/glumpy/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-h16j98cf/glumpy/setup.py", line 9, in <module>
        from Cython.Distutils import build_ext
    ModuleNotFoundError: No module named 'Cython'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
failed
CondaEnvException: Pip failed`

**Comment by HartmannSa** [comment]
I found a work-around:

in the environment.yaml I deleted line 48 
`      - glumpy==1.1.0`

With this change the command 
`conda env create -n cosypose --file environment.yaml`
works. (Environment needs to be removed before with 
`conda remove --name cosypose --all`)

I tried to install glumpy afterwards with
`conda install -n cosypose glumpy==1.1.0`
however I got the Error:
`PackagesNotFoundError: The following packages are not available from current channels:
  - glumpy==1.1.0
Current channels:
  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://conda.anaconda.org/conda-forge/linux-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://conda.anaconda.org/pytorch/linux-64
  - https://conda.anaconda.org/pytorch/noarch`

Activating the cosypose environment and then using
`pip install glumpy==1.1.0` 
works, but I am not sure if this is the same..

**Comment by JohannesAman** [comment]
I resolved this by putting Cython in the dependencies section in the environment.yaml file

**Comment by mypey** [comment]
I solved this problem by upgrading the glumpy library up to `glumpy==1.2.0` in the `environment.yml` file.
