### ISSUE TITLE
eigenpy import Error libboost_python-py27: undefined symbol: PyClass_Type

### ISSUE THREAD

**Issue by HartmannSa** [ylabbe/cosypose#23]
Hi,

I installed and downloaded everything as mentioned in the readme.
The command 
`python -m cosypose.scripts.run_cosypose_eval --config tless-siso`

leads to this Error:
Setting OMP and MKL num threads to 1.
Traceback (most recent call last):
  File "/home/rosmatch/anaconda3/envs/cosypose/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/rosmatch/anaconda3/envs/cosypose/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/rosmatch/cosypose/cosypose/scripts/run_cosypose_eval.py", line 20, in <module>
    from cosypose.lib3d import Transform
  File "/home/rosmatch/cosypose/cosypose/lib3d/__init__.py", line 1, in <module>
    from .transform import Transform, parse_pose_args
  File "/home/rosmatch/cosypose/cosypose/lib3d/transform.py", line 3, in <module>
    import eigenpy
  File "/opt/ros/melodic/lib/python2.7/dist-packages/eigenpy/__init__.py", line 17, in <module>
    from .eigenpy import *
ImportError: /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.65.1: undefined symbol: PyClass_Type

The error message also occurs with other commands like 
`python -m cosypose.scripts.run_cosypose_eval --config tless-vivo --nviews=4` 
and probably all scripts which include " from cosypose.lib3d import Transform"...

I could imagine the problem is that eigenpy is loaded from the dist-packages of python2.7, but the desired python version is 3.7. But I don't know how to change this and whether this is really the reason for the error message.

I am running on Ubuntu 18.04.5 LTS.

**Comment by jcarpent** [comment]
You should unset your PYTHONPATH env variable. It is currently pointing to `/opt/ros/melodic/lib/python2.7/dist-packages/`

**Comment by HartmannSa** [comment]
Thanks, this solved it for me!

**Comment by jcarpent** [comment]
Good news! I will now close this issue as it seems to be solved.
