### ISSUE TITLE
Training on T-LESS PBR dataset

### ISSUE THREAD

**Issue by azad96** [ylabbe/cosypose#29]
I want to train the single-view 6D pose estimation models with PBR dataset instead of the synthetic images mentioned in the repo. Hence, I skipped the synthetic data generation part and tried to start the training with the following command (I did not use runjob as I have a single gpu)
`
python -m cosypose.scripts.run_pose_training --config tless-coarse
`
This results in the following error
~~~
Setting OMP and MKL num threads to 1.
pybullet build time: Dec 20 2020 13:52:50
0:00:00.000927 - Training with config: tless-coarse 
0:00:00.001180 - --------------------------------------------------------------------------------
0:00:00.001214 - resume_run_id: None
0:00:00.001235 - urdf_ds_name: tless.cad
0:00:00.001254 - object_ds_name: tless.cad
0:00:00.001271 - n_symmetries_batch: 64
0:00:00.001290 - train_ds_names: [('synthetic.tless-1M.train', 1), ('tless.primesense.train', 5)]
0:00:00.001307 - val_ds_names: [('synthetic.tless-1M.val', 1)]
0:00:00.001324 - val_epoch_interval: 10
0:00:00.001340 - test_ds_names: ['tless.primesense.test']
0:00:00.001357 - test_epoch_interval: 30
0:00:00.001373 - n_test_frames: None
0:00:00.001389 - input_resize: (540, 720)
0:00:00.001406 - rgb_augmentation: True
0:00:00.001422 - background_augmentation: True
0:00:00.001438 - gray_augmentation: False
0:00:00.001453 - backbone_str: efficientnet-b3
0:00:00.001469 - run_id_pretrain: None
0:00:00.001485 - n_pose_dims: 9
0:00:00.001501 - n_rendering_workers: 8
0:00:00.001517 - refiner_run_id_for_test: None
0:00:00.001533 - coarse_run_id_for_test: None
0:00:00.001552 - lr: 0.0003
0:00:00.001568 - weight_decay: 0.0
0:00:00.001585 - n_epochs_warmup: 50
0:00:00.001600 - lr_epoch_decay: 500
0:00:00.001617 - clip_grad_norm: 0.5
0:00:00.001633 - batch_size: 32
0:00:00.001649 - epoch_size: 115200
0:00:00.001665 - n_epochs: 700
0:00:00.001681 - n_dataloader_workers: 8
0:00:00.001697 - loss_disentangled: True
0:00:00.001712 - n_points_loss: 2600
0:00:00.001728 - TCO_input_generator: fixed
0:00:00.001743 - n_iterations: 1
0:00:00.001759 - min_area: None
0:00:00.001774 - run_id: tless-coarse--309342
0:00:00.001790 - train_refiner: False
0:00:00.001806 - train_coarse: True
0:00:00.001828 - save_dir: /home/azad/Desktop/cosypose/local_data/experiments/tless-coarse--309342
0:00:00.001844 - --------------------------------------------------------------------------------
0:00:01.385036 - Connection established with 1 gpus.
Traceback (most recent call last):
  File "/home/azad/anaconda3/envs/cosypose/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/azad/anaconda3/envs/cosypose/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/azad/Desktop/cosypose/cosypose/scripts/run_pose_training.py", line 207, in <module>
    train_pose(cfg)
  File "/home/azad/Desktop/cosypose/cosypose/training/train_pose.py", line 226, in train_pose
    scene_ds_train = make_datasets(args.train_ds_names)
  File "/home/azad/Desktop/cosypose/cosypose/training/train_pose.py", line 220, in make_datasets
    ds = make_scene_dataset(ds_name)
  File "/home/azad/Desktop/cosypose/cosypose/datasets/datasets_cfg.py", line 139, in make_scene_dataset
    ds = SyntheticSceneDataset(ds_dir=LOCAL_DATA_DIR / 'synt_datasets' / ds_name, train=is_train)
  File "/home/azad/Desktop/cosypose/cosypose/datasets/synthetic_dataset.py", line 21, in __init__
    keys = pkl.loads(keys_path.read_bytes())
  File "/home/azad/anaconda3/envs/cosypose/lib/python3.7/pathlib.py", line 1209, in read_bytes
    with self.open(mode='rb') as f:
  File "/home/azad/anaconda3/envs/cosypose/lib/python3.7/pathlib.py", line 1203, in open
    opener=self._opener)
  File "/home/azad/anaconda3/envs/cosypose/lib/python3.7/pathlib.py", line 1058, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/home/azad/Desktop/cosypose/local_data/synt_datasets/tless-1M/train_keys.pkl'
~~~
Should I download this file from somewhere? and do I need to make changes as I want to use PBR?

**Comment by azad96** [comment]
By the way, this is solved by using the bop- config format in run_pose_training.py instead of tless- option.
