### ISSUE TITLE
BOP20 Running evaluation (locally)

### ISSUE THREAD

**Issue by trevor-taeyeop** [ylabbe/cosypose#3]
I got error while evaluating locally. 
Can I ask how to handle this part??

**[Command]**
`python -m cosypose.scripts.run_bop20_eval --result_id=bop-synt+real-nviews=8--763684  --method=maskrcnn_detections/multiview --dataset ycbv`

**[Error Message]**
`FileNotFoundError: [Errno 2] No such file or directory: '/sdata1/workspace/cosypose/local_data/bop_eval_outputs/challenge2020_ycbv-test/error=vsd_ntop=-1_delta=15.000_tau=0.050/errors_000048.json'
`

**[Error Location]**
https://github.com/ylabbe/bop_toolkit_challenge20/blob/f114991b3eea186184127cddfe6a10e2d640e656/scripts/eval_calc_scores.py#L241

**[Terminal Message]**
```
(cosypose) user@user:/sdata1/workspace/cosypose$ sh eval_bop_ycb_pose.sh 
Predictions from: /sdata1/workspace/cosypose/local_data/results/bop-synt+real-nviews=8--763684/dataset=ycbv/results.pth.tar
Method: maskrcnn_detections/multiview
Number of predictions:  9073
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 9073/9073 [00:02<00:00, 3249.72it/s]
Wrote: 
8/28|17:28:04: ===========
8/28|17:28:04: EVALUATING: /sdata1/workspace/cosypose/local_data/bop_predictions_csv/challenge2020_ycbv-test.csv
8/28|17:28:04: ===========
8/28|17:28:04: Running: python scripts/eval_calc_errors.py --n_top=-1 --error_type=vsd --result_filenames=/sdata1/workspace/cosypose/local_data/bop_predictions_csv/challenge2020_ycbv-test.csv --renderer_type=python --results_path=/sdata1/workspace/cosypose/local_data/bop_predictions_csv --eval_path=/sdata1/workspace/cosypose/local_data/bop_eval_outputs --targets_filename=test_targets_bop19.json --max_sym_disc_step=0.01 --skip_missing=1 --vsd_deltas=hb:15,icbin:15,icmi:15,itodd:5,lm:15,lmo:15,ruapc:15,tless:15,tudl:15,tyol:15,ycbv:15 --vsd_taus=0.05,0.1,0.15000000000000002,0.2,0.25,0.3,0.35000000000000003,0.4,0.45,0.5 --vsd_normalized_by_diameter=True
8/28|17:28:04: -----------
8/28|17:28:04: Parameters:
8/28|17:28:04: - n_top: -1
8/28|17:28:04: - error_type: vsd
8/28|17:28:04: - vsd_deltas: {'hb': 15.0, 'icbin': 15.0, 'icmi': 15.0, 'itodd': 5.0, 'lm': 15.0, 'lmo': 15.0, 'ruapc': 15.0, 'tless': 15.0, 'tudl': 15.0, 'tyol': 15.0, 'ycbv': 15.0}
8/28|17:28:04: - vsd_taus: [0.05, 0.1, 0.15000000000000002, 0.2, 0.25, 0.3, 0.35000000000000003, 0.4, 0.45, 0.5]
8/28|17:28:04: - vsd_normalized_by_diameter: True
8/28|17:28:04: - max_sym_disc_step: 0.01
8/28|17:28:04: - skip_missing: True
8/28|17:28:04: - renderer_type: python
8/28|17:28:04: - result_filenames: ['/sdata1/workspace/cosypose/local_data/bop_predictions_csv/challenge2020_ycbv-test.csv']
8/28|17:28:04: - results_path: /sdata1/workspace/cosypose/local_data/bop_predictions_csv
8/28|17:28:04: - eval_path: /sdata1/workspace/cosypose/local_data/bop_eval_outputs
8/28|17:28:04: - datasets_path: /sdata1/workspace/cosypose/local_data/bop_datasets
8/28|17:28:04: - targets_filename: test_targets_bop19.json
8/28|17:28:04: - out_errors_tpath: {eval_path}/{result_name}/{error_sign}/errors_{scene_id:06d}.json
8/28|17:28:04: -----------
8/28|17:28:04: Processing: /sdata1/workspace/cosypose/local_data/bop_predictions_csv/challenge2020_ycbv-test.csv
8/28|17:28:04: Initializing renderer...
[w] b'GLX: Failed to create context: BadValue (integer parameter out of range for operation)'
[x] Window creation failed
8/28|17:28:05: Running: python scripts/eval_calc_scores.py --error_dir_paths=challenge2020_ycbv-test/error=vsd_ntop=-1_delta=15.000_tau=0.050 --eval_path=/sdata1/workspace/cosypose/local_data/bop_eval_outputs --targets_filename=test_targets_bop19.json --visib_gt_min=-1 --correct_th_vsd=0.05
8/28|17:28:05: -----------
8/28|17:28:05: Parameters:
8/28|17:28:05: - correct_th: {'vsd': [0.05], 'mssd': [0.2], 'mspd': [10.0], 'cus': [0.5], 'rete': [5.0, 5.0], 're': [5.0], 'te': [5.0], 'proj': [5.0], 'ad': [0.1], 'add': [0.1], 'adi': [0.1]}
8/28|17:28:05: - normalized_by_diameter: ['ad', 'add', 'adi', 'mssd']
8/28|17:28:05: - normalized_by_im_width: ['mspd']
8/28|17:28:05: - visib_gt_min: -1.0
8/28|17:28:05: - error_dir_paths: ['challenge2020_ycbv-test/error=vsd_ntop=-1_delta=15.000_tau=0.050']
8/28|17:28:05: - eval_path: /sdata1/workspace/cosypose/local_data/bop_eval_outputs
8/28|17:28:05: - datasets_path: /sdata1/workspace/cosypose/local_data/bop_datasets
8/28|17:28:05: - targets_filename: test_targets_bop19.json
8/28|17:28:05: - error_tpath: {eval_path}/{error_dir_path}/errors_{scene_id:06d}.json
8/28|17:28:05: - out_matches_tpath: {eval_path}/{error_dir_path}/matches_{score_sign}.json
8/28|17:28:05: - out_scores_tpath: {eval_path}/{error_dir_path}/scores_{score_sign}.json
8/28|17:28:05: -----------
8/28|17:28:05: Processing: challenge2020_ycbv-test/error=vsd_ntop=-1_delta=15.000_tau=0.050
8/28|17:28:05: Calculating score - error: vsd, method: challenge2020, dataset: ycbv.
8/28|17:28:05: Organizing estimation targets...
8/28|17:28:05: Processing scene 48 of ycbv...
Traceback (most recent call last):
  File "scripts/eval_calc_scores.py", line 223, in <module>
    scene_errs = inout.load_json(scene_errs_path, keys_to_int=True)
  File "/sdata1/workspace/cosypose/deps/bop_toolkit_challenge/bop_toolkit_lib/inout.py", line 77, in load_json
    with open(path, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/sdata1/workspace/cosypose/local_data/bop_eval_outputs/challenge2020_ycbv-test/error=vsd_ntop=-1_delta=15.000_tau=0.050/errors_000048.json'
Traceback (most recent call last):
  File "/sdata1/workspace/cosypose/deps/bop_toolkit_challenge/scripts/eval_bop19.py", line 212, in <module>
    raise RuntimeError('Calculation of scores failed.')
RuntimeError: Calculation of scores failed.
```

**Comment by ylabbe** [comment]
Are you trying to run this on a machine without display ? I see you have this error
```
[w] b'GLX: Failed to create context: BadValue (integer parameter out of range for operation)
[x] Window creation failed
```
The code uses the python renderer of the [bop toolkit](https://github.com/thodan/bop_toolkit) which requires a X server running (and have the `DISPLAY` environnement variable set correctly). If you are running it on a headless server you should try to compile their C++ renderer and use the proper flag when calling the evaluation script. You should try to make the example of the bop toolkit work first.

**Comment by naaths** [comment]
Hello, may I ask, can this code directly train and evaluate the linemod dataset? Thank you
