### ISSUE TITLE
No such file or directory while reproducing Multiview results

### ISSUE THREAD

**Issue by JohannesAma** [ylabbe/cosypose#50]
With python -m cosypose.scripts.run_cosypose_eval --config tless-vivo --nviews=4
I get the error: 

(cosypose) amann@ipf-photolab-05:~/cosypose$ python -m cosypose.scripts.run_bop_inference_JA --config tless-pbr
Setting OMP and MKL num threads to 1.
pybullet build time: Dec  1 2020 13:20:08
0:00:01.382220 - Save dir: /home/amann/cosypose/local_data/results/tless-pbr--280187
0:00:01.382380 - --------------------------------------------------------------------------------
0:00:01.382415 - n_workers: 8
0:00:01.382439 - pred_bsz: 1
0:00:01.382460 - n_frames: None
0:00:01.382480 - n_groups: None
0:00:01.382499 - skip_evaluation: False
0:00:01.382518 - external_predictions: True
0:00:01.382536 - n_coarse_iterations: 1
0:00:01.382554 - n_refiner_iterations: 4
0:00:01.382574 - icp: False
0:00:01.382592 - debug: False
0:00:01.382612 - n_views: 1
0:00:01.382630 - ds_name: hb.bop19
0:00:01.382652 - save_dir: /home/amann/cosypose/local_data/results/tless-pbr--280187/dataset=hb
0:00:01.382671 - detector_run_id: detector-bop-tless-pbr--873074
0:00:01.382689 - coarse_run_id: coarse-bop-tless-pbr--506801
0:00:01.382708 - refiner_run_id: refiner-bop-tless-pbr--233420
0:00:01.382726 - --------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/amann/anaconda3/envs/cosypose/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/amann/anaconda3/envs/cosypose/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/amann/cosypose/cosypose/scripts/run_bop_inference_JA.py", line 270, in <module>
    main()
  File "/home/amann/cosypose/cosypose/scripts/run_bop_inference_JA.py", line 266, in main
    run_inference(this_cfg)
  File "/home/amann/cosypose/cosypose/scripts/run_bop_inference_JA.py", line 105, in run_inference
    scene_ds = make_scene_dataset(args.ds_name, n_frames=args.n_frames)
  File "/home/amann/cosypose/cosypose/datasets/datasets_cfg.py", line 74, in make_scene_dataset
    ds = BOPDataset(ds_dir, split='test_primesense')
  File "/home/amann/cosypose/cosypose/datasets/bop.py", line 62, in __init__
    assert ds_dir.exists(), 'Dataset does not exists.'
AssertionError: Dataset does not exists.
(cosypose) amann@ipf-photolab-05:~/cosypose$ python -m cosypose.scripts.run_cosypose_eval --config tless-vivo --nviews=4
Setting OMP and MKL num threads to 1.
pybullet build time: Dec  1 2020 13:20:08
0:00:00.000692 - Starting ...
0:00:01.383520 - SAVE DIR: /home/amann/cosypose/local_data/results/tless-vivo-n_views=4--1851779338
0:00:01.383580 - Coarse: tless-coarse--10219
0:00:01.383623 - Refiner: tless-refiner--585928
0:00:01.715244 - Building index and loading annotations...
[Memory]2.0s, 0.0min    : Loading build_index...
Traceback (most recent call last):
  File "/home/amann/anaconda3/envs/cosypose/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/amann/anaconda3/envs/cosypose/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/amann/cosypose/cosypose/scripts/run_cosypose_eval.py", line 491, in <module>
    main()
  File "/home/amann/cosypose/cosypose/scripts/run_cosypose_eval.py", line 332, in main
    scene_ds = make_scene_dataset(ds_name)
  File "/home/amann/cosypose/cosypose/datasets/datasets_cfg.py", line 41, in make_scene_dataset
    ds = _make_tless_dataset('test_primesense')
  File "/home/amann/cosypose/cosypose/datasets/datasets_cfg.py", line 18, in _make_tless_dataset
    ds = BOPDataset(ds_dir, split=split)
  File "/home/amann/cosypose/cosypose/datasets/bop.py", line 74, in __init__
    self.frame_index = pd.read_feather(save_file_index).reset_index(drop=True)
  File "/home/amann/anaconda3/envs/cosypose/lib/python3.7/site-packages/pandas/util/_decorators.py", line 208, in wrapper
    return func(*args, **kwargs)
  File "/home/amann/anaconda3/envs/cosypose/lib/python3.7/site-packages/pandas/io/feather_format.py", line 119, in read_feather
    return feather.read_feather(path, columns=columns, use_threads=bool(use_threads))
  File "/home/amann/anaconda3/envs/cosypose/lib/python3.7/site-packages/pyarrow/feather.py", line 214, in read_feather
    reader = FeatherReader(source)
  File "/home/amann/anaconda3/envs/cosypose/lib/python3.7/site-packages/pyarrow/feather.py", line 40, in __init__
    self.open(source)
  File "pyarrow/error.pxi", line 80, in pyarrow.lib.check_status
  File "pyarrow/io.pxi", line 1406, in pyarrow.lib.get_reader
  File "pyarrow/io.pxi", line 1395, in pyarrow.lib._get_native_file
  File "pyarrow/io.pxi", line 788, in pyarrow.lib.memory_map
  File "pyarrow/io.pxi", line 751, in pyarrow.lib.MemoryMappedFile._open
  File "pyarrow/error.pxi", line 80, in pyarrow.lib.check_status
pyarrow.lib.ArrowIOError: Failed to open local file '/home/amann/cosypose/local_data/bop_datasets/tless/index_test_primesense.feather', error: No such file or directory

I guess there is a problem with the test_primesense folder, I already deleted it and downloaded all available tless files again, but it didn't help.
Trying to run the inference I get an Error to.

Traceback (most recent call last):
  File "/home/amann/anaconda3/envs/cosypose/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/amann/anaconda3/envs/cosypose/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/amann/cosypose/cosypose/scripts/run_bop_inference_JA.py", line 270, in <module>
    main()
  File "/home/amann/cosypose/cosypose/scripts/run_bop_inference_JA.py", line 266, in main
    run_inference(this_cfg)
  File "/home/amann/cosypose/cosypose/scripts/run_bop_inference_JA.py", line 105, in run_inference
    scene_ds = make_scene_dataset(args.ds_name, n_frames=args.n_frames)
  File "/home/amann/cosypose/cosypose/datasets/datasets_cfg.py", line 74, in make_scene_dataset
    ds = BOPDataset(ds_dir, split='test_primesense')
  File "/home/amann/cosypose/cosypose/datasets/bop.py", line 62, in __init__
    assert ds_dir.exists(), 'Dataset does not exists.'
AssertionError: Dataset does not exists.

I guess both Errors point to the test_primesense combined with the bop.py File.

**Comment by JohannesAma** [comment]
I deleted Cosypose and set it up again, now it is working.
