### ISSUE TITLE
BOP Dataset not downloading

### ISSUE THREAD

**Issue by MikaYeghi** [ylabbe/cosypose#76]
Hi! 
I am trying to download the BOP Challenge dataset by running `python -m cosypose.scripts.download --bop_dataset=tless`, but in return I get the following error:

```
(cosypose-new) yemika@nitro:~/*my_path*/cosypose$ python -m cosypose.scripts.download --bop_dataset=tless
Setting OMP and MKL num threads to 1.
0:00:00.001069 - Download http://ptak.felk.cvut.cz/6DB/public/bop_datasets/tless_base.zip at /home/yemika/Mikael/Oxford/Studying/4YP/code/cosypose/local_data/downloads/tless_base.zip...
Traceback (most recent call last):
  File "/home/yemika/Public/anaconda3/envs/cosypose-new/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/yemika/Public/anaconda3/envs/cosypose-new/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/yemika/Mikael/Oxford/Studying/4YP/code/cosypose/cosypose/scripts/download.py", line 196, in <module>
    main()
  File "/home/yemika/Mikael/Oxford/Studying/4YP/code/cosypose/cosypose/scripts/download.py", line 81, in main
    download_bop_original(args.bop_dataset, args.pbr_training_images and BOP_DATASETS[args.bop_dataset].get('has_pbr', True))
  File "/home/yemika/Mikael/Oxford/Studying/4YP/code/cosypose/cosypose/scripts/download.py", line 170, in download_bop_original
    wget_download_and_extract(BOP_SRC + filename, BOP_DS_DIR)
  File "/home/yemika/Mikael/Oxford/Studying/4YP/code/cosypose/cosypose/scripts/download.py", line 189, in wget_download_and_extract
    wget.download(url, out=tmp_path.as_posix())
  File "/home/yemika/Public/anaconda3/envs/cosypose-new/lib/python3.7/site-packages/wget.py", line 526, in download
    (tmpfile, headers) = ulib.urlretrieve(binurl, tmpfile, callback)
  File "/home/yemika/Public/anaconda3/envs/cosypose-new/lib/python3.7/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/home/yemika/Public/anaconda3/envs/cosypose-new/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/home/yemika/Public/anaconda3/envs/cosypose-new/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/home/yemika/Public/anaconda3/envs/cosypose-new/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/home/yemika/Public/anaconda3/envs/cosypose-new/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/home/yemika/Public/anaconda3/envs/cosypose-new/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/home/yemika/Public/anaconda3/envs/cosypose-new/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

It used to work well before, but now something has changed. Following the link from which it tries to download the data I get:

![Screenshot from 2022-09-19 16-31-42](https://user-images.githubusercontent.com/64435576/191029217-b34e283a-baa8-4dd1-b7a1-87f3512ffc04.png)

**Comment by bibekyess** [comment]
Hi @MikaYeghi I also faced this error. But we can download it from the bop dataset official link: [https://bop.felk.cvut.cz/datasets/](https://bop.felk.cvut.cz/datasets/). You can either use the command lines or download manually.

**Comment by Toefinder** [comment]
> Hi @MikaYeghi I also faced this error. But we can download it from the bop dataset official link: https://bop.felk.cvut.cz/datasets/. You can either use the command lines or download manually.

I created a [PR](https://github.com/Simple-Robotics/cosypose/pull/7) to fix this in the Simple-Robotics official fork, but no maintainer has merged or commented on it so far.
